"""
narrative.py — AI-generated language for fingerprint results.

All user-facing text is generated by Cohere using the real computed signals.
Falls back to templates silently so the fingerprint endpoint never fails.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from typing import Optional

log = logging.getLogger("vantage")

_llm = None


def _get_llm():
    global _llm
    if _llm is None:
        from langchain_cohere import ChatCohere
        _llm = ChatCohere(
            model="command-a-03-2025",
            cohere_api_key=os.environ.get("COHERE_API_KEY", ""),
            temperature=0.3,
            max_tokens=600,
        )
    return _llm


@dataclass
class NarrativeResult:
    dna_summary:            str
    improvement_hint:       str
    explainer_dna:          str
    explainer_opportunities: str
    explainer_comparison:   str
    explainer_locations:    str
    explainer_risk:         str


def generate_dna_narrative(
    *,
    mode: str,
    category: str,
    top_categories: list[dict],
    n_locations: int,
    gold_standard_match_pct: int,
    client_weight: float,
    data_confidence: str,
    gap_cats: list[str],
    resolved_suburbs: dict[str, str],
    failure_summary: Optional[str],
) -> NarrativeResult:
    try:
        return _call_llm(
            mode=mode, category=category, top_categories=top_categories,
            n_locations=n_locations, gold_standard_match_pct=gold_standard_match_pct,
            client_weight=client_weight, data_confidence=data_confidence,
            gap_cats=gap_cats, resolved_suburbs=resolved_suburbs,
            failure_summary=failure_summary,
        )
    except Exception as exc:
        log.warning(f"narrative generation failed ({exc}), using fallback")
        return _fallback(
            mode=mode, category=category, top_categories=top_categories,
            n_locations=n_locations, gold_standard_match_pct=gold_standard_match_pct,
            gap_cats=gap_cats, failure_summary=failure_summary,
        )


def _call_llm(
    *,
    mode: str,
    category: str,
    top_categories: list[dict],
    n_locations: int,
    gold_standard_match_pct: int,
    client_weight: float,
    data_confidence: str,
    gap_cats: list[str],
    resolved_suburbs: dict[str, str],
    failure_summary: Optional[str],
) -> NarrativeResult:
    top_names   = [t["category"] for t in top_categories[:5]]
    top_weights = [round(t["weight"] * 100, 1) for t in top_categories[:5]]
    best_suburbs = list(resolved_suburbs.values())[:6]

    mode_context = {
        "existing": f"The franchise owner uploaded {n_locations} of their own Australian stores.",
        "fresh":    "No existing stores — analysis uses the Australian industry benchmark.",
        "overseas": "The franchise is expanding from overseas into Australia.",
    }.get(mode, "")

    confidence_context = {
        "HIGH":   "High confidence (5+ stores).",
        "MEDIUM": "Medium confidence (2–4 stores).",
        "LOW":    "Low confidence (≤1 store) — treat as indicative.",
    }.get(data_confidence, "")

    gap_line = (
        "Gap vs benchmark: " + ", ".join(gap_cats) + " are underrepresented."
        if gap_cats else
        "DNA closely matches the benchmark — no significant gaps."
    )

    suburb_line = (
        f"Geocoded stores: {', '.join(best_suburbs)}" if best_suburbs else
        "No geocoded stores."
    )

    prompt = f"""You are a location intelligence analyst for Vantage, a franchise expansion platform.

Write 7 short pieces of copy for a {category} franchise owner reviewing their location DNA report.
All copy must reference the REAL data below — no generic filler.

=== ANALYSIS DATA ===
Mode: {mode} — {mode_context}
Top DNA drivers: {', '.join(f"{n} ({w}%)" for n, w in zip(top_names, top_weights))}
Gold standard match: {gold_standard_match_pct}%
Confidence: {data_confidence} — {confidence_context}
{suburb_line}
{gap_line}
{f"Risk note: {failure_summary}" if failure_summary else "No underperforming locations uploaded."}

=== OUTPUT FORMAT ===
Output exactly 7 lines. Each line is one piece of copy. No labels, no numbering, no markdown.

Line 1 — DNA SUMMARY (≤28 words): What the owner's commercial DNA IS. Reference the actual top categories. Insight, not template.
Line 2 — IMPROVEMENT HINT (≤22 words): One concrete, actionable thing to look for in new locations. Reference gap categories if any.
Line 3 — EXPLAINER: DNA CARD (≤35 words): Explain WHY the top DNA drivers matter for a {category} business. Make it specific to this category.
Line 4 — EXPLAINER: WHERE TO LOOK CARD (≤35 words): Explain how the suburb scoring works and what the tiers mean for this owner's expansion strategy.
Line 5 — EXPLAINER: HOW YOU COMPARE CARD (≤35 words): Explain what {gold_standard_match_pct}% means in plain terms. What does this score tell the owner about their current locations?
Line 6 — EXPLAINER: LOCATIONS USED CARD (≤30 words): Explain how the {n_locations} uploaded location(s) were used to build the DNA and why more locations improve accuracy.
Line 7 — EXPLAINER: RISK PATTERNS CARD (≤30 words): Explain what the underperforming location analysis does and why avoiding similar suburbs matters. {"Use the risk note above." if failure_summary else "Write a general explanation since no risk locations were uploaded."}

Tone: McKinsey analyst — confident, direct, data-backed. No fluff. No "Vantage" mentions. No chatbot language."""

    from langchain_core.messages import HumanMessage
    llm = _get_llm()
    response = llm.invoke([HumanMessage(content=prompt)])
    lines = [l.strip() for l in response.content.strip().split("\n") if l.strip()]

    # Pad with fallback text if the model returned fewer lines than expected
    fb = _fallback(
        mode=mode, category=category, top_categories=top_categories,
        n_locations=n_locations, gold_standard_match_pct=gold_standard_match_pct,
        gap_cats=gap_cats, failure_summary=failure_summary,
    )
    defaults = [
        fb.dna_summary, fb.improvement_hint, fb.explainer_dna,
        fb.explainer_opportunities, fb.explainer_comparison,
        fb.explainer_locations, fb.explainer_risk,
    ]
    while len(lines) < 7:
        lines.append(defaults[len(lines)])

    return NarrativeResult(
        dna_summary=lines[0],
        improvement_hint=lines[1],
        explainer_dna=lines[2],
        explainer_opportunities=lines[3],
        explainer_comparison=lines[4],
        explainer_locations=lines[5],
        explainer_risk=lines[6],
    )


def _fallback(
    *,
    mode: str,
    category: str,
    top_categories: list[dict],
    n_locations: int,
    gold_standard_match_pct: int,
    gap_cats: list[str],
    failure_summary: Optional[str],
) -> NarrativeResult:
    top_names = [t["category"] for t in top_categories[:3]]
    cat_l = category.lower()

    if mode == "fresh":
        dna_summary = (
            f"Top-performing {cat_l} businesses in Australia cluster near "
            f"{', '.join(top_names)}." if top_names else
            f"Industry benchmark for {category} analysed across 7,734 Australian suburbs."
        )
    elif mode == "overseas":
        dna_summary = (
            f"Your overseas DNA maps to an Australian environment anchored by "
            f"{', '.join(top_names)}." if top_names else
            "Your overseas DNA has been translated to Australian equivalents."
        )
    else:
        dna_summary = (
            f"Your stores share a commercial DNA built around "
            f"{', '.join(top_names)}." if top_names else
            "Your franchise DNA has been analysed and mapped."
        )

    improvement_hint = (
        f"Prioritise suburbs with more {', '.join(gap_cats)} to close the gap with top performers."
        if gap_cats else
        "Your location profile closely matches the industry benchmark for this category."
    )

    explainer_dna = (
        f"These are the business types most commonly found near {'your best' if mode == 'existing' else 'top-performing'} "
        f"{cat_l} locations. A high concentration of these nearby is a strong success signal."
    )

    explainer_opportunities = (
        f"Every Australian suburb was scored against your DNA. "
        f"'Top opportunities' beat the benchmark. 'Avoid' areas show risk signals like high closure rates or oversaturation."
    )

    score_label = "very strong" if gold_standard_match_pct >= 80 else "solid" if gold_standard_match_pct >= 60 else "moderate"
    explainer_comparison = (
        f"At {gold_standard_match_pct}%, your location profile is a {score_label} match to Australia's best {cat_l} businesses. "
        f"Above 70% means your stores are in commercially similar environments to the top performers."
    )

    explainer_locations = (
        f"{'These' if n_locations > 1 else 'This'} {n_locations} location{'s' if n_locations != 1 else ''} "
        f"{'were' if n_locations > 1 else 'was'} geocoded and used to build your DNA vector. "
        f"More locations sharpen accuracy."
    )

    explainer_risk = (
        "Patterns from your underperforming locations are used to flag similar suburbs — "
        "helping you avoid repeating the same mistakes in new markets."
        if failure_summary else
        "Upload your underperforming locations and we'll flag any suburb that shares their commercial DNA — "
        "so you avoid repeating the same mistakes."
    )

    return NarrativeResult(
        dna_summary=dna_summary,
        improvement_hint=improvement_hint,
        explainer_dna=explainer_dna,
        explainer_opportunities=explainer_opportunities,
        explainer_comparison=explainer_comparison,
        explainer_locations=explainer_locations,
        explainer_risk=explainer_risk,
    )


# ── Location signal insights ──────────────────────────────────────────────────

def generate_location_insights(
    *,
    locality: str,
    state: str,
    category: str,
    composite_score: float,        # 0-1
    tier: str,
    signals: list[dict],           # [{name, score, badge, extra}]
    top_categories: list[dict],    # [{category, count}]
    competitor_count: int,
    data_confidence: str,
) -> dict:
    """
    Returns {
        "signal_insights": {signal_name: insight_str},
        "recommendation":  str,
    }
    Falls back to template strings on any error.
    """
    try:
        return _call_llm_location(
            locality=locality, state=state, category=category,
            composite_score=composite_score, tier=tier, signals=signals,
            top_categories=top_categories, competitor_count=competitor_count,
            data_confidence=data_confidence,
        )
    except Exception as exc:
        log.warning(f"location narrative failed ({exc}), using fallback")
        return _fallback_location(
            locality=locality, category=category,
            composite_score=composite_score, signals=signals,
        )


def _call_llm_location(
    *,
    locality: str,
    state: str,
    category: str,
    composite_score: float,
    tier: str,
    signals: list[dict],
    top_categories: list[dict],
    competitor_count: int,
    data_confidence: str,
) -> dict:
    score_pct = round(composite_score * 100)

    def _sig_line(s: dict) -> str:
        note = " [INVERTED: high score = LOW risk = SAFE; low score = HIGH risk = DANGEROUS]" \
            if s["name"] == "Risk Signals" else ""
        return f"  - {s['name']}: {round(s['score'] * 100)}/100 ({s['badge']}){note}"

    sig_lines = "\n".join(_sig_line(s) for s in signals)
    top_cat_line = ", ".join(
        f"{c['category']} ({c['count']} venues)" for c in top_categories[:6]
    ) or "No data"

    tier_label = {
        "BETTER_THAN_BEST": "Top Opportunity — outperforms the benchmark",
        "STRONG": "Strong — solid expansion candidate",
        "WATCH": "Watch — proceed with caution",
        "AVOID": "Avoid — risk signals elevated",
    }.get(tier, tier)

    prompt = f"""You are a location intelligence analyst. Write plain-English insights for a franchise expansion report.

=== SUBURB ===
{locality}, {state}
Category: {category}
Overall score: {score_pct}/100 — {tier_label}
Data confidence: {data_confidence}
Nearby businesses: {top_cat_line}
Direct competitors: {competitor_count}

=== SIGNAL SCORES ===
{sig_lines}

=== TASK ===
Write exactly 6 lines. No labels, no numbering, no markdown.

Line 1 — Fingerprint Match insight (≤20 words): What does this score mean for a {category} here? Reference the actual score and nearby business types.
Line 2 — Market Trajectory insight (≤20 words): What does the trajectory score tell the owner about timing and growth momentum in {locality}?
Line 3 — Competitive Pressure insight (≤20 words): Interpret the competition score. Mention the {competitor_count} competitor(s) and what that means for market entry.
Line 4 — Ecosystem Diversity insight (≤20 words): What does the diversity score mean for foot traffic and cross-category customers in {locality}?
Line 5 — Risk Signals insight (≤20 words): CRITICAL — this score is INVERTED. Score ≥65 means LOW risk (write positively: safe, stable, low closure). Score <40 means HIGH risk (write as a warning). Never describe a high score as risky.
Line 6 — Overall Recommendation (≤40 words): A direct, actionable verdict for a {category} franchise owner considering {locality}. Mention the score. Specific, not generic.

Tone: direct, data-backed, no hedging. Write as if advising a real founder."""

    from langchain_core.messages import HumanMessage
    llm = _get_llm()
    response = llm.invoke([HumanMessage(content=prompt)])
    lines = [l.strip() for l in response.content.strip().split("\n") if l.strip()]

    names = ["Fingerprint Match", "Market Trajectory", "Competitive Pressure",
             "Ecosystem Diversity", "Risk Signals"]
    fb = _fallback_location(
        locality=locality, category=category,
        composite_score=composite_score, signals=signals,
    )
    signal_insights = {}
    for i, name in enumerate(names):
        signal_insights[name] = lines[i] if i < len(lines) else fb["signal_insights"].get(name, "")
    recommendation = lines[5] if len(lines) >= 6 else fb["recommendation"]

    return {"signal_insights": signal_insights, "recommendation": recommendation}


def _fallback_location(
    *,
    locality: str,
    category: str,
    composite_score: float,
    signals: list[dict],
) -> dict:
    score_map = {s["name"]: s["score"] for s in signals}

    def _sig(name: str, high: str, mid: str, low: str) -> str:
        s = score_map.get(name, 0.5)
        return high if s >= 0.65 else mid if s >= 0.40 else low

    signal_insights = {
        "Fingerprint Match": _sig(
            "Fingerprint Match",
            f"{locality}'s business mix closely resembles your best-performing locations.",
            "Some commercial similarities to your locations, though the environment differs noticeably.",
            "This suburb's business mix looks very different from your successful locations.",
        ),
        "Market Trajectory": _sig(
            "Market Trajectory",
            "New businesses are opening consistently — demand is growing and the market is healthy.",
            "Business openings and closures are roughly balanced — steady but not accelerating.",
            "More businesses are closing than opening here — the local market may be contracting.",
        ),
        "Competitive Pressure": _sig(
            "Competitive Pressure",
            f"Very few direct {category} competitors nearby — room to enter an open market.",
            "Some competitors present, but not saturated. Room to establish a foothold.",
            f"{category} is heavily represented here. Strong differentiation will be critical.",
        ),
        "Ecosystem Diversity": _sig(
            "Ecosystem Diversity",
            "A rich mix of complementary businesses drives natural foot traffic.",
            "A reasonable variety of businesses that can support trade.",
            "Limited business variety — fewer complementary venues to drive foot traffic.",
        ),
        "Risk Signals": _sig(
            "Risk Signals",
            "Low closure rates and stable conditions — minimal operational risk.",
            "Moderate risk indicators. Worth monitoring before committing to a lease.",
            "High closure rates or saturation detected. Elevated operational risk.",
        ),
    }

    score_pct = round(composite_score * 100)
    verdict = (
        "Top-tier match — move quickly." if score_pct >= 80 else
        "Strong candidate worth a site inspection." if score_pct >= 60 else
        "Solid fundamentals with some headwinds. Proceed cautiously." if score_pct >= 40 else
        "Not recommended under current market conditions."
    )
    recommendation = (
        f"{locality} scores {score_pct}/100 for {category}. {verdict}"
    )

    return {"signal_insights": signal_insights, "recommendation": recommendation}
